
[functions.send-otp-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-otp-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-otp-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-otp-email/*.html" ]

[functions.send-recovery-otp]
enabled = true
verify_jwt = false
import_map = "./functions/send-recovery-otp/deno.json"
entrypoint = "./functions/send-recovery-otp/index.ts"

[functions.verify-recovery-otp]
enabled = true
verify_jwt = false
import_map = "./functions/verify-recovery-otp/deno.json"
entrypoint = "./functions/verify-recovery-otp/index.ts"

[functions.complete-recovery-password]
enabled = true
verify_jwt = false
import_map = "./functions/complete-recovery-password/deno.json"
entrypoint = "./functions/complete-recovery-password/index.ts"

[functions.send-otp]
enabled = true
verify_jwt = false
import_map = "./functions/send-otp/deno.json"
entrypoint = "./functions/send-otp/index.ts"

[functions.verify-otp]
enabled = true
verify_jwt = false
import_map = "./functions/verify-otp/deno.json"
entrypoint = "./functions/verify-otp/index.ts"

[functions.delete-account]
enabled = true
verify_jwt = true
import_map = "./functions/delete-account/deno.json"
entrypoint = "./functions/delete-account/index.ts"

[functions.low-stock-expo-push]
enabled = true
verify_jwt = false
import_map = "./functions/low-stock-expo-push/deno.json"
entrypoint = "./functions/low-stock-expo-push/index.ts"

[functions.send-owner-push]
enabled = true
verify_jwt = false
import_map = "./functions/send-owner-push/deno.json"
entrypoint = "./functions/send-owner-push/index.ts"

[functions.paynow-initiate]
enabled = true
verify_jwt = false
import_map = "./functions/paynow-initiate/deno.json"
entrypoint = "./functions/paynow-initiate/index.ts"

[functions.paynow-poll]
enabled = true
verify_jwt = false
import_map = "./functions/paynow-poll/deno.json"
entrypoint = "./functions/paynow-poll/index.ts"

[functions.paynow-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/paynow-webhook/deno.json"
entrypoint = "./functions/paynow-webhook/index.ts"

[functions.active-session]
enabled = true
verify_jwt = true
entrypoint = "./functions/active-session/index.ts"

[functions.shopkeeper-auth]
enabled = true
verify_jwt = false
entrypoint = "./functions/shopkeeper-auth/index.ts"
